CC = g++
LIBS = -pthread

all: orca-server-mahimahi-http-compmon

orca-server-mahimahi-http-compmon:
	${CC} ${LIBS} orca-server-mahimahi-http-compmon.cc flow.cc -o ../orca-server-mahimahi-http-compmon
