# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: compmon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcompmon.proto\x12\x07\x63ompmon\"c\n\tSARReport\x12\x11\n\treport_id\x18\x01 \x01(\x05\x12\x14\n\x0cinput_states\x18\x02 \x03(\x02\x12\x14\n\x0c\x61\x63tion_taken\x18\x03 \x01(\x02\x12\x17\n\x0freward_recieved\x18\x04 \x01(\x02\"\x1c\n\x0bReportReply\x12\r\n\x05reply\x18\x01 \x01(\t2?\n\x07\x43ompMon\x12\x34\n\x06Report\x12\x12.compmon.SARReport\x1a\x14.compmon.ReportReply\"\x00\x62\x06proto3')



_SARREPORT = DESCRIPTOR.message_types_by_name['SARReport']
_REPORTREPLY = DESCRIPTOR.message_types_by_name['ReportReply']
SARReport = _reflection.GeneratedProtocolMessageType('SARReport', (_message.Message,), {
  'DESCRIPTOR' : _SARREPORT,
  '__module__' : 'compmon_pb2'
  # @@protoc_insertion_point(class_scope:compmon.SARReport)
  })
_sym_db.RegisterMessage(SARReport)

ReportReply = _reflection.GeneratedProtocolMessageType('ReportReply', (_message.Message,), {
  'DESCRIPTOR' : _REPORTREPLY,
  '__module__' : 'compmon_pb2'
  # @@protoc_insertion_point(class_scope:compmon.ReportReply)
  })
_sym_db.RegisterMessage(ReportReply)

_COMPMON = DESCRIPTOR.services_by_name['CompMon']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SARREPORT._serialized_start=26
  _SARREPORT._serialized_end=125
  _REPORTREPLY._serialized_start=127
  _REPORTREPLY._serialized_end=155
  _COMPMON._serialized_start=157
  _COMPMON._serialized_end=220
# @@protoc_insertion_point(module_scope)
